name: GitHub Profile Summary Cards

on:
  create:
  schedule:
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Github Cards
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update README
        uses: vn7n24fzkq/github-profile-summary-cards@master
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_SUMMARY_CARDS_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
